# Generated by Django 2.1.1 on 2018-09-19 21:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last modified')),
                ('name', models.CharField(max_length=50, verbose_name="Flower's name")),
                ('image', models.URLField(blank=True, help_text='An image of the flower', verbose_name='Image')),
                ('period', models.DurationField(help_text='Defines how frequently water the flower', verbose_name='Water period')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='MessengerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last modified')),
                ('page_id', models.CharField(help_text='Facebook page ID', max_length=50, verbose_name='Page ID')),
                ('psid', models.CharField(help_text='Page scoped user ID', max_length=50, verbose_name='User ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='messengeruser',
            unique_together={('page_id', 'psid')},
        ),
        migrations.AddField(
            model_name='flower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger_bot.MessengerUser'),
        ),
    ]
